### ISSUE TITLE
Ruby: Implement `init` command

### ISSUE THREAD

**Issue by torchello** [applandinc/appmap-ruby#139]
## Description
Creates a base appmap.yml configuration for the current project. The name property is derived from a git remote, and the package paths from the current project directory.

## Output
`.appmap.yml`:
```yaml
name: my_git_project

packages:
  - path: app/models
  - path: app/controllers

```
